apiVersion: v1
kind: Namespace
metadata:
  name: intranet-website
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: intranet-website
  namespace: intranet-website
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  replicas: 3
  selector:
    matchLabels:
      app: intranet-website
  template:
    metadata:
      labels:
        app: intranet-website
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - intranet-website
              topologyKey: kubernetes.io/hostname
      containers:
        - name: intranet-website
          image: attiss/techxchange-3670-intranet-website
          ports:
            - containerPort: 8080
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: intranet-website
  namespace: intranet-website
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: intranet-website
